
CREATE OR REPLACE PROCEDURE spMaakGebruiker (
  P_GEBRUIKERSNAAM    VARCHAR2(255),
  P_ADRESID           INTEGER,
  P_VOORNAAM          VARCHAR2(255),
  P_TUSSENVOEGSEL     VARCHAR2(15),
  P_ACHTERNAAM        VARCHAR2(255),
  P_GEBOORTEDATUM     DATE,
  P_GESLACHT          CHAR(1),
  P_MAILADRES         VARCHAR2(255),
  P_TELEFOONNUMMER    INTEGER --Wordt later hopelijk: VARCHAR2(20)
) AS BEGIN
  --INSERT INTO GEBRUIKER (GEBRUIKERSNAAM, ADRESID, VOORNAAM, TUSSENVOEGSEL, ACHTERNAAM, GEBOORTEDATUM, GESLACHT, MAILADRES) VALUES
  --  (P_GEBRUIKERSNAAM, P_ADRESID, P_VOORNAAM, P_TUSSENVOEGSEL, P_ACHTERNAAM, P_GEBOORTEDATUM, P_GESLACHT, P_MAILADRES);
  --INSERT INTO TELEFOON (TELEFOONNUMMER, GEBRUIKERSNAAM, KVKNUMMER) VALUES
  --  (P_TELEFOONNUMMER, P_GEBRUIKERSNAAM, NULL);
END;