--Constraint ...: Iedere gebruiker moet minimaal één telefoonnummer hebben.
CREATE OR REPLACE PROCEDURE SP_MAAK_GEBRUIKER (
  P_GEBRUIKERSNAAM    VARCHAR2,
  P_ADRESID           INTEGER,
  P_VOORNAAM          VARCHAR2,
  P_TUSSENVOEGSEL     VARCHAR2,
  P_ACHTERNAAM        VARCHAR2,
  P_GEBOORTEDATUM     DATE,
  P_GESLACHT          CHAR,
  P_MAILADRES         VARCHAR2,
  P_TELEFOONNUMMER    INTEGER --Wordt later hopelijk: VARCHAR2(20)
) AS BEGIN
  INSERT INTO GEBRUIKER (GEBRUIKERSNAAM, ADRESID, VOORNAAM, TUSSENVOEGSEL, ACHTERNAAM, GEBOORTEDATUM, GESLACHT, MAILADRES) VALUES
    (P_GEBRUIKERSNAAM, P_ADRESID, P_VOORNAAM, P_TUSSENVOEGSEL, P_ACHTERNAAM, P_GEBOORTEDATUM, P_GESLACHT, P_MAILADRES);
  INSERT INTO TELEFOON (TELEFOONNUMMER, GEBRUIKERSNAAM, KVKNUMMER) VALUES
    (P_TELEFOONNUMMER, P_GEBRUIKERSNAAM, NULL);
END SP_MAAK_GEBRUIKER;