ALTER TABLE PROJECT
DROP trigger trAutomaticSubscription

CREATE TRIGGER trAutomaticSubscription
ON PROJECTROL_VAN_GEBRUIKER

AFTER INSERT, UPDATE
AS
	DECLARE @radius INTEGER
	SELECT @radius = 1
	BEGIN TRY
		INSERT INTO PROJECTROL_VAN_GEBRUIKER(GEBRUIKERSNAAM, PROJECTID, ROLNAAM, DATUMAANVRAAG, DATUMUITGAVE, AUTOMATISCHTOEGEVOEGD)
			SELECT GEBRUIKERSNAAM, (SELECT PROJECTID FROM INSERTED), 'BELANGHEBBENDE', GETDATE(), GETDATE(), 1
			FROM ADRES_VAN_GEBRUIKER
			WHERE GEBRUIKERSNAAM NOT IN (SELECT GEBRUIKERSNAAM 
										 FROM PROJECTROL_VAN_GEBRUIKER
										 WHERE PROJECTID = (SELECT PROJECTID FROM INSERTED) 
										 AND ROLNAAM = 'INITIATIEFNEMER'
										 )
			AND
			
			ADRESID NOT IN (
				SELECT ADRESID
				FROM ADRES
				EXCEPT
				SELECT ADRESID
				FROM ADRES
				WHERE XCOORDINAAT < (SELECT XCOORDINAAT - @radius
									 FROM PROJECT
									 WHERE PROJECTID = (SELECT PROJECTID FROM INSERTED) 
									)
				OR XCOORDINAAT > (SELECT XCOORDINAAT + @radius
								   FROM PROJECT
								   WHERE PROJECTID = (SELECT PROJECTID FROM INSERTED)
								  )
				AND YCOORDINAAT < (SELECT YCOORDINAAT - @radius
								   FROM PROJECT
								   WHERE PROJECTID = (SELECT PROJECTID FROM INSERTED)
								   )
				OR YCOORDINAAT > (SELECT YCOORDINAAT + @radius
								   FROM PROJECT
								   WHERE PROJECTID = (SELECT PROJECTID FROM INSERTED)
								  ) 
						)
											
			END TRY
			BEGIN CATCH
				THROW;
				ROLLBACK
			END CATCH
GO


--Nieuwe user wordt via een SP toegevoegd, dus trigger hoeft niet getest te worden op multiple inserts
CREATE TRIGGER trAutomaticSubscriptionForNewUsers
ON ADRES_VAN_GEBRUIKER

AFTER INSERT, UPDATE
AS
	DECLARE @radius INTEGER
	SELECT @radius = 1
	BEGIN TRY
		INSERT INTO ABONNEMENT(GEBRUIKERSNAAM, PROJECTID, DATUMAANVRAAG, DATUMUITGAVE, AUTOMATISCHTOEGEVOEGD)
			SELECT GEBRUIKERSNAAM, (SELECT PROJECTID FROM PROJECT), GETDATE(), GETDATE(), 1
			FROM ADRES_VAN_GEBRUIKER
			WHERE ADRESID IN (
				SELECT ADRESID
				FROM ADRESGEGEVENS
				EXCEPT
				SELECT ADRESID
				FROM ADRESGEGEVENS
				WHERE XCOORDINAAT < (SELECT XCOORDINAAT - 1
									 FROM PROJECT AS P
									)
				OR XCOORDINAAT > (SELECT XCOORDINAAT + 1
								   FROM PROJECT
								  )
				AND YCOORDINAAT < (SELECT YCOORDINAAT - 1
								   FROM PROJECT
								   )
				OR YCOORDINAAT > (SELECT YCOORDINAAT + 1
								   FROM PROJECT
								  )
				)				
	END TRY
	BEGIN CATCH
		THROW;
	END CATCH
GO

 
SELECT * FROM ADRES_VAN_GEBRUIKER
SELECT * FROM PROJECT
SELECT * FROM ADRESGEGEVENS





	INSERT INTO ADRESGEGEVENS(POSTCODE, HUISNUMMER, XCOORDINAAT, YCOORDINAAT)
	VALUES('0000AA', 1, 50, 50)

	INSERT INTO ADRES_VAN_GEBRUIKER(ADRESID, GEBRUIKERSNAAM)
	VALUES(1012, 'Michieltje2')

	'Michieltje2'



INSERT INTO ABONNEMENT(GEBRUIKERSNAAM, PROJECTID, DATUMAANVRAAG, DATUMUITGAVE, AUTOMATISCHTOEGEVOEGD)
			SELECT GEBRUIKERSNAAM, (SELECT PROJECTID FROM PROJECT), GETDATE(), GETDATE(), 1
			FROM ADRES_VAN_GEBRUIKER
			WHERE ADRESID IN (
				SELECT ADRESID
				FROM ADRESGEGEVENS
				EXCEPT
				SELECT ADRESID
				FROM ADRESGEGEVENS
				WHERE XCOORDINAAT < (SELECT XCOORDINAAT - 1
									 FROM PROJECT AS P
									)
				OR XCOORDINAAT > (SELECT XCOORDINAAT + 1
								   FROM PROJECT
								  )
				AND YCOORDINAAT < (SELECT YCOORDINAAT - 1
								   FROM PROJECT
								   )
				OR YCOORDINAAT > (SELECT YCOORDINAAT + 1
								   FROM PROJECT
								  )
				)				

				SELECT XCOORDINAAT, YCOORDINAAT
				FROM PROJECT
				EXCEPT
				SELECT XCOORDINAAT, YCOORDINAAT
				FROM ADRESGEGEVENS 
				WHERE XCOORDINAAT < (SELECT XCOORDINAAT + 1
									 FROM PROJECT AS P
									)
				OR XCOORDINAAT > (SELECT XCOORDINAAT - 1
								   FROM PROJECT
								  )
				AND YCOORDINAAT < (SELECT YCOORDINAAT + 1
								   FROM PROJECT
								   )
				OR YCOORDINAAT > (SELECT YCOORDINAAT - 1
								   FROM PROJECT
								  )


				SELECT *
				FROM PROJECT
				EXCEPT
				SELECT PROJECTID
				FROM ADRESGEGEVENS
				WHERE XCOORDINAAT 