-- Testscript voor spAddUserToProject
SET NOCOUNT ON

-- Succes scenario
GO
DECLARE @TRANCOUNT INTEGER = @@TRANCOUNT;
IF (@TRANCOUNT = 0)
	BEGIN TRAN
ELSE
	SAVE TRAN savepoint;
BEGIN TRY
	
	--Aanmaken van de voorbeelddata

	--GEBRUIKER
	DECLARE @GEBRUIKERSNAAM VARCHAR(255) = 'CEO'
	DECLARE @WACHTWOORD VARCHAR(255) = 'WACHTWOORD'
	DECLARE @MAILADRES VARCHAR(255) = 'MAILADRES'

	DECLARE @GEBRUIKERSNAAM2 VARCHAR(255) = 'TWEEDEACCOUNT'
	DECLARE @WACHTWOORD2 VARCHAR(255) = 'WACHTWOORD'
	DECLARE @MAILADRES2 VARCHAR(255) = 'MAILADRES@HOTMAIL.COM'

	INSERT INTO GEBRUIKER(GEBRUIKERSNAAM, WACHTWOORD, MAILADRES)
	VALUES(@GEBRUIKERSNAAM, @WACHTWOORD, @MAILADRES),
		  (@GEBRUIKERSNAAM2, @WACHTWOORD2, @MAILADRES2)

	--PARTICULIER
	DECLARE @VOORNAAM VARCHAR(255) = 'Ricardo'
	DECLARE @TUSSENVOEGSEL VARCHAR(25) = 'van'
	DECLARE @ACHTERNAAM VARCHAR(255) = 'BuriK'
	DECLARE @GEBOORTEDATUM DATE = '1996-11-29'
	DECLARE @GESLACHT CHAR(1) = 'M'

	DECLARE @VOORNAAM2 VARCHAR(255) = 'Testgebruiker'
	DECLARE @TUSSENVOEGSEL2 VARCHAR(25) = 'van'
	DECLARE @ACHTERNAAM2 VARCHAR(255) = 'Han'
	DECLARE @GEBOORTEDATUM2 DATE = GETDATE()
	DECLARE @GESLACHT2 CHAR(1) = 'M'
	
	INSERT INTO PARTICULIER
	VALUES(@GEBRUIKERSNAAM, @VOORNAAM, @TUSSENVOEGSEL, @ACHTERNAAM, @GEBOORTEDATUM, @GESLACHT),
		  (@GEBRUIKERSNAAM2, @VOORNAAM2, @TUSSENVOEGSEL2, @ACHTERNAAM2, @GEBOORTEDATUM2, @GESLACHT2)

	--PROJECT
	DECLARE @PROJECTTITEL VARCHAR(255) =  'TITEL'
	DECLARE @AANGEMAAKTOP DATE = GETDATE()
	DECLARE @WERKZAAMHEID VARCHAR(255) = 'Het testen van de procedure'
	DECLARE @XCOORDINAAT FLOAT = 12.15468
	DECLARE @YCOORDINAAT FLOAT = 12.6875213

	INSERT INTO PROJECT
	VALUES(@PROJECTTITEL, @AANGEMAAKTOP, @WERKZAAMHEID, @XCOORDINAAT, @YCOORDINAAT)

	DECLARE @PROJECTID INTEGER = SCOPE_IDENTITY()

	--ROL
	DECLARE @ROLNAAM VARCHAR(255) = 'INITIATIEFNEMER'
	DECLARE @ROLBESCHRIJVING VARCHAR(255) = 'TESTWAARDE VOOR EEN INITIATIEFNEMER'

	DECLARE @ROLNAAM2 VARCHAR(255) = 'BELANGHEBBENDE'
	DECLARE @ROLBESCHRIJVING2 VARCHAR(255) = 'TESTWAARDE VOOR EEN INITIATIEFNEMER'

	INSERT INTO ROL
	VALUES(@ROLNAAM, @ROLBESCHRIJVING),
		  (@ROLNAAM2, @ROLBESCHRIJVING2)

	--PROJECTROL VAN GEBRUIKER
	DECLARE @AUTOMATISCHTOEGEVOEGD BIT = 1
	DECLARE @DATUMAANVRAAG DATE = GETDATE()

	EXEC spAddUserToProject @gebruikersnaam = @GEBRUIKERSNAAM2, @projectid = @PROJECTID, @rolnaam = @ROLNAAM2
	
	PRINT 'Test 1 is geslaagd.'
	IF (@TRANCOUNT = 0)
		ROLLBACK TRAN
	ELSE
		ROLLBACK TRAN savepoint;
END TRY
BEGIN CATCH
PRINT 'Test 1 is gefaald!';
	IF (@TRANCOUNT = 0)
		ROLLBACK TRAN
	ELSE
		ROLLBACK TRAN savepoint;
	THROW;
END CATCH
GO

--Will fail
-- Testscript voor spAddUserToProject
SET NOCOUNT ON

-- Succes scenario
GO
DECLARE @TRANCOUNT INTEGER = @@TRANCOUNT;
IF (@TRANCOUNT = 0)
	BEGIN TRAN
ELSE
	SAVE TRAN savepoint;
BEGIN TRY
	
	--Aanmaken van de voorbeelddata

	--GEBRUIKER
	DECLARE @GEBRUIKERSNAAM VARCHAR(255) = 'CEO'
	DECLARE @WACHTWOORD VARCHAR(255) = 'WACHTWOORD'
	DECLARE @MAILADRES VARCHAR(255) = 'MAILADRES'

	DECLARE @GEBRUIKERSNAAM2 VARCHAR(255) = 'TWEEDEACCOUNT'
	DECLARE @WACHTWOORD2 VARCHAR(255) = 'WACHTWOORD'
	DECLARE @MAILADRES2 VARCHAR(255) = 'MAILADRES@HOTMAIL.COM'

	INSERT INTO GEBRUIKER(GEBRUIKERSNAAM, WACHTWOORD, MAILADRES)
	VALUES(@GEBRUIKERSNAAM, @WACHTWOORD, @MAILADRES),
		  (@GEBRUIKERSNAAM2, @WACHTWOORD2, @MAILADRES2)

	--PARTICULIER
	DECLARE @VOORNAAM VARCHAR(255) = 'Ricardo'
	DECLARE @TUSSENVOEGSEL VARCHAR(25) = 'van'
	DECLARE @ACHTERNAAM VARCHAR(255) = 'BuriK'
	DECLARE @GEBOORTEDATUM DATE = '1996-11-29'
	DECLARE @GESLACHT CHAR(1) = 'M'

	DECLARE @VOORNAAM2 VARCHAR(255) = 'Testgebruiker'
	DECLARE @TUSSENVOEGSEL2 VARCHAR(25) = 'van'
	DECLARE @ACHTERNAAM2 VARCHAR(255) = 'Han'
	DECLARE @GEBOORTEDATUM2 DATE = GETDATE()
	DECLARE @GESLACHT2 CHAR(1) = 'M'
	
	INSERT INTO PARTICULIER
	VALUES(@GEBRUIKERSNAAM, @VOORNAAM, @TUSSENVOEGSEL, @ACHTERNAAM, @GEBOORTEDATUM, @GESLACHT),
		  (@GEBRUIKERSNAAM2, @VOORNAAM2, @TUSSENVOEGSEL2, @ACHTERNAAM2, @GEBOORTEDATUM2, @GESLACHT2)

	--PROJECT
	DECLARE @PROJECTTITEL VARCHAR(255) =  'TITEL'
	DECLARE @AANGEMAAKTOP DATE = GETDATE()
	DECLARE @WERKZAAMHEID VARCHAR(255) = 'Het testen van de procedure'
	DECLARE @XCOORDINAAT FLOAT = 12.15468
	DECLARE @YCOORDINAAT FLOAT = 12.6875213

	EXEC spAddProject @gebruikersnaam = @GEBRUIKERSNAAM, @titel = @PROJECTTITEL, @werkzaamheid = @WERKZAAMHEID, @xcoordinaat = @XCOORDINAAT, @ycoordinaat = @YCOORDINAAT

	DECLARE @PROJECTID INTEGER = SCOPE_IDENTITY()

	--ROL
	DECLARE @ROLNAAM VARCHAR(255) = 'INITIATIEFNEMER'
	DECLARE @ROLBESCHRIJVING VARCHAR(255) = 'TESTWAARDE VOOR EEN INITIATIEFNEMER'

	INSERT INTO ROL
	VALUES(@ROLNAAM, @ROLBESCHRIJVING)

	--PROJECTROL VAN GEBRUIKER
	DECLARE @AUTOMATISCHTOEGEVOEGD BIT = 1
	DECLARE @DATUMAANVRAAG DATE = GETDATE()

	EXEC spAddUserToProject @gebruikersnaam = @GEBRUIKERSNAAM2, @projectid = @PROJECTID, @rolnaam = @ROLNAAM
	SELECT * FROM PROJECTROL_VAN_GEBRUIKER

	PRINT 'Test 2 is gefaald!.'
	IF (@TRANCOUNT = 0)
		ROLLBACK TRAN
	ELSE
		ROLLBACK TRAN savepoint;
END TRY
BEGIN CATCH
PRINT 'Test 2 is geslaagd!';
	IF (@TRANCOUNT = 0)
		ROLLBACK TRAN
	ELSE
		ROLLBACK TRAN savepoint;
	THROW;
END CATCH
GO

