-- Testscript voor spAddUserToProject
SET NOCOUNT ON

-- Succes scenario
GO
DECLARE @TRANCOUNT INTEGER = @@TRANCOUNT;
IF (@TRANCOUNT = 0)
	BEGIN TRAN
ELSE
	SAVE TRAN savepoint;
BEGIN TRY
	
	--Aanmaken van de voorbeelddata

	--GEBRUIKER
	DECLARE @GEBRUIKERSNAAM VARCHAR(255) = 'Ricardo'
	DECLARE @VOORNAAM VARCHAR(100) = 'Ricardo'
	DECLARE @TUSSENVOEGSEL VARCHAR(25) = 'van'
	DECLARE @ACHTERNAAM VARCHAR(255) = 'Burik'
	DECLARE @GEBOORTEDATUM DATE = '1996-11-29'
	DECLARE @GESLACHT CHAR(1) = 'M'
	DECLARE @MAILADRES VARCHAR(255) = 'ricardovanburik@hotmail.com'
	DECLARE @WACHTWOORD VARCHAR(255) = 'wachtwoord'
	DECLARE @TELEFOON VARCHAR(20) = '0655871782'
	DECLARE @POSTCODE VARCHAR(6) = '7334AA'
	DECLARE @HUISNUMMER INTEGER = 284
	DECLARE @TOEVOEGING VARCHAR(5) = 'A'
	DECLARE @XCOORDINAAT FLOAT = 12.15468
	DECLARE @YCOORDINAAT FLOAT = 12.6875213

	EXEC spInsertUser @gebruikersnaam = @GEBRUIKERSNAAM, @voornaam = @VOORNAAM, @tussenvoegsel = @TUSSENVOEGSEL, @achternaam = @ACHTERNAAM,
				      @geboortedatum = @GEBOORTEDATUM, @geslacht = @GESLACHT, @mailadres = @MAILADRES, @wachtwoord = @WACHTWOORD, @telefoon = @TELEFOON,
					  @postcode = @POSTCODE, @huisnummer = @HUISNUMMER, @toevoeging = @TOEVOEGING, @xcoordinaat = @XCOORDINAAT, @ycoordinaat = @YCOORDINAAT
	
	PRINT 'Test 1 is geslaagd.'
	IF (@TRANCOUNT = 0)
		ROLLBACK TRAN
	ELSE
		ROLLBACK TRAN savepoint;
END TRY
BEGIN CATCH
PRINT 'Test 1 is gefaald!';
	IF (@TRANCOUNT = 0)
		ROLLBACK TRAN
	ELSE
		ROLLBACK TRAN savepoint;
	THROW;
END CATCH
GO

-- Test faalt op 
SET NOCOUNT ON

-- Succes scenario
GO
DECLARE @TRANCOUNT INTEGER = @@TRANCOUNT;
IF (@TRANCOUNT = 0)
	BEGIN TRAN
ELSE
	SAVE TRAN savepoint;
BEGIN TRY
	
	--Aanmaken van de voorbeelddata

	--GEBRUIKER
	DECLARE @GEBRUIKERSNAAM VARCHAR(255) = 'Rico'
	DECLARE @VOORNAAM VARCHAR(100) = 'Ricardo'
	DECLARE @TUSSENVOEGSEL VARCHAR(25) = 'van'
	DECLARE @ACHTERNAAM VARCHAR(255) = 'Burik'
	DECLARE @GEBOORTEDATUM DATE = '1996-11-29'
	DECLARE @GESLACHT CHAR(1) = 'M'
	DECLARE @MAILADRES VARCHAR(255) = 'ricardovanburik@hotmail.com'
	DECLARE @WACHTWOORD VARCHAR(255) = 'wachtwoord'
	DECLARE @TELEFOON VARCHAR(20) = '0655871782'
	DECLARE @POSTCODE VARCHAR(6) = '7334AA'
	DECLARE @HUISNUMMER INTEGER = 284
	DECLARE @TOEVOEGING VARCHAR(5) = 'A'
	DECLARE @XCOORDINAAT FLOAT = 12.15468
	DECLARE @YCOORDINAAT FLOAT = 12.6875213

	DECLARE @GEBRUIKERSNAAM2 VARCHAR(255) = 'Ricardo'
	DECLARE @VOORNAAM2 VARCHAR(100) = 'Ricardo'
	DECLARE @TUSSENVOEGSEL2 VARCHAR(25) = 'van'
	DECLARE @ACHTERNAAM2 VARCHAR(255) = 'Burik'
	DECLARE @GEBOORTEDATUM2 DATE = '1996-11-29'
	DECLARE @GESLACHT2 CHAR(1) = 'M'
	DECLARE @MAILADRES2 VARCHAR(255) = 'ricardovanburik1@hotmail.com'
	DECLARE @WACHTWOORD2 VARCHAR(255) = 'wachtwoord'
	DECLARE @TELEFOON2 VARCHAR(20) = '0655871782'
	DECLARE @POSTCODE2 VARCHAR(6) = '7334AA'
	DECLARE @HUISNUMMER2 INTEGER = 284
	DECLARE @TOEVOEGING2 VARCHAR(5) = 'A'
	DECLARE @XCOORDINAAT2 FLOAT = 12.15468
	DECLARE @YCOORDINAAT2 FLOAT = 12.6875213

	EXEC spInsertUser @gebruikersnaam = @GEBRUIKERSNAAM, @voornaam = @VOORNAAM, @tussenvoegsel = @TUSSENVOEGSEL, @achternaam = @ACHTERNAAM,
				      @geboortedatum = @GEBOORTEDATUM, @geslacht = @GESLACHT, @mailadres = @MAILADRES, @wachtwoord = @WACHTWOORD, @telefoon = @TELEFOON,
					  @postcode = @POSTCODE, @huisnummer = @HUISNUMMER, @toevoeging = @TOEVOEGING, @xcoordinaat = @XCOORDINAAT, @ycoordinaat = @YCOORDINAAT
	
	
	EXEC spInsertUser @gebruikersnaam = @GEBRUIKERSNAAM2, @voornaam = @VOORNAAM2, @tussenvoegsel = @TUSSENVOEGSEL2, @achternaam = @ACHTERNAAM2,
				      @geboortedatum = @GEBOORTEDATUM2, @geslacht = @GESLACHT2, @mailadres = @MAILADRES2, @wachtwoord = @WACHTWOORD2, @telefoon = @TELEFOON2,
					  @postcode = @POSTCODE2, @huisnummer = @HUISNUMMER2, @toevoeging = @TOEVOEGING2, @xcoordinaat = @XCOORDINAAT2, @ycoordinaat = @YCOORDINAAT2
	

	PRINT 'Test 2 is gefaald.'
	IF (@TRANCOUNT = 0)
		ROLLBACK TRAN
	ELSE
		ROLLBACK TRAN savepoint;
END TRY
BEGIN CATCH
PRINT 'Test 2 is geslaagd!';
	IF (@TRANCOUNT = 0)
		ROLLBACK TRAN
	ELSE
		ROLLBACK TRAN savepoint;
	THROW;
END CATCH
GO

-- 

SET NOCOUNT ON

-- Succes scenario
GO
DECLARE @TRANCOUNT INTEGER = @@TRANCOUNT;
IF (@TRANCOUNT = 0)
	BEGIN TRAN
ELSE
	SAVE TRAN savepoint;
BEGIN TRY
	
	--Aanmaken van de voorbeelddata

	--GEBRUIKER
	DECLARE @GEBRUIKERSNAAM VARCHAR(255) = 'Rico'
	DECLARE @VOORNAAM VARCHAR(100) = 'Ricardo'
	DECLARE @TUSSENVOEGSEL VARCHAR(25) = 'van'
	DECLARE @ACHTERNAAM VARCHAR(255) = 'Burik'
	DECLARE @GEBOORTEDATUM DATE = '1996-11-29'
	DECLARE @GESLACHT CHAR(1) = 'M'
	DECLARE @MAILADRES VARCHAR(255) = 'ricardovanburik@hotmail.com'
	DECLARE @WACHTWOORD VARCHAR(255) = 'wachtwoord'
	DECLARE @TELEFOON VARCHAR(20) = '0655871782'
	DECLARE @POSTCODE VARCHAR(6) = '7334AA'
	DECLARE @HUISNUMMER INTEGER = 284
	DECLARE @TOEVOEGING VARCHAR(5) = 'A'
	DECLARE @XCOORDINAAT FLOAT = 12.15468
	DECLARE @YCOORDINAAT FLOAT = 12.6875213

	DECLARE @GEBRUIKERSNAAM2 VARCHAR(255) = 'Ricardo'
	DECLARE @VOORNAAM2 VARCHAR(100) = 'Ricardo'
	DECLARE @TUSSENVOEGSEL2 VARCHAR(25) = 'van'
	DECLARE @ACHTERNAAM2 VARCHAR(255) = 'Burik'
	DECLARE @GEBOORTEDATUM2 DATE = '1996-11-29'
	DECLARE @GESLACHT2 CHAR(1) = 'M'
	DECLARE @MAILADRES2 VARCHAR(255) = 'ricardovanburik1@hotmail.com'
	DECLARE @WACHTWOORD2 VARCHAR(255) = 'wachtwoord'
	DECLARE @TELEFOON2 VARCHAR(20) = '0655871782'
	DECLARE @POSTCODE2 VARCHAR(6) = '7334AA'
	DECLARE @HUISNUMMER2 INTEGER = 284
	DECLARE @TOEVOEGING2 VARCHAR(5) = 'A'
	DECLARE @XCOORDINAAT2 FLOAT = 12.15468
	DECLARE @YCOORDINAAT2 FLOAT = 12.6875213

	EXEC spInsertUser @gebruikersnaam = @GEBRUIKERSNAAM, @voornaam = @VOORNAAM, @tussenvoegsel = @TUSSENVOEGSEL, @achternaam = @ACHTERNAAM,
				      @geboortedatum = @GEBOORTEDATUM, @geslacht = @GESLACHT, @mailadres = @MAILADRES, @wachtwoord = @WACHTWOORD, @telefoon = @TELEFOON,
					  @postcode = @POSTCODE, @huisnummer = @HUISNUMMER, @toevoeging = @TOEVOEGING, @xcoordinaat = @XCOORDINAAT, @ycoordinaat = @YCOORDINAAT
	
	
	EXEC spInsertUser @gebruikersnaam = @GEBRUIKERSNAAM2, @voornaam = @VOORNAAM2, @tussenvoegsel = @TUSSENVOEGSEL2, @achternaam = @ACHTERNAAM2,
				      @geboortedatum = @GEBOORTEDATUM2, @geslacht = @GESLACHT2, @mailadres = @MAILADRES2, @wachtwoord = @WACHTWOORD2, @telefoon = @TELEFOON2,
					  @postcode = @POSTCODE2, @huisnummer = @HUISNUMMER2, @toevoeging = @TOEVOEGING2, @xcoordinaat = @XCOORDINAAT2, @ycoordinaat = @YCOORDINAAT2
	

	PRINT 'Test 3 is gefaald.'
	IF (@TRANCOUNT = 0)
		ROLLBACK TRAN
	ELSE
		ROLLBACK TRAN savepoint;
END TRY
BEGIN CATCH
PRINT 'Test 3 is geslaagd!';
	IF (@TRANCOUNT = 0)
		ROLLBACK TRAN
	ELSE
		ROLLBACK TRAN savepoint;
	THROW;
END CATCH
GO

