SELECT * FROM PROJECTROL_VAN_GEBRUIKER

SELECT * FROM ROL

SELECT * FROM VERGUNNING

CREATE PROCEDURE spPermitDecision
@vergunningsid INTEGER,
@status VARCHAR(255),
@omschrijvingNieuw VARCHAR(4000),
@datumverloop DATE
AS
	BEGIN TRY
		DECLARE @OMSCHRIJVING VARCHAR(4000)
		SELECT @OMSCHRIJVING = OMSCHRIJVING 
		FROM VERGUNNING	WHERE VERGUNNINGSID = @vergunningsid

		UPDATE VERGUNNING
		SET OMSCHRIJVING = @OMSCHRIJVING + ' | ' + @STATUS + ': ' + @omschrijvingNieuw

		IF(@status = 'GOEDGEKEURD')
			BEGIN
				UPDATE VERGUNNING
				SET DATUMUITGAVE = GETDATE(), DATUMVERLOOP = @datumverloop
				WHERE VERGUNNINGSID = @vergunningsid	
			END
	END TRY
	BEGIN CATCH
		THROW;
		ROLLBACK
	END CATCH
GO	

DECLARE @OMSCHRIJVING VARCHAR(255)
SELECT @OMSCHRIJVING = OMSCHRIJVING FROM VERGUNNING WHERE VERGUNNINGSID = 1

UPDATE VERGUNNING
SET OMSCHRIJVING = @OMSCHRIJVING + ' ' + 'AFGEKEURD OMDAT:'
WHERE VERGUNNINGSID = 1