CREATE PROCEDURE spAddUserToProject
@gebruikersnaam VARCHAR(255), 
@projectid INTEGER, 
@rolnaam VARCHAR(255)
AS
	BEGIN TRY
		INSERT INTO PROJECTROL_VAN_GEBRUIKER (GEBRUIKERSNAAM, PROJECTID, ROLNAAM, DATUMAANVRAAG, AUTOMATISCHTOEGEVOEGD)
		VALUES(@gebruikersnaam, @projectid, @rolnaam, GETDATE(), 0)
	END TRY
	BEGIN CATCH
		THROW;
		ROLLBACK
	END CATCH
GO

